# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:15.6
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
     - "5432:5432"
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: odp
#   db-init:
#     image: aoh83/spring-init:latest
#     depends_on:
#       - db
#     environment:
#       # HOST DB
#       PGPASSWORD: example
#       PGUSER: postgres
#       PGDB: postgres
#       PGPORT: 5432
#       # SPRING DB TO SETUP
#       DB_USER: odp
#       DB_DATABASE: odp



